from typing import Protocol, List, Optional, Dict, Any
from domain.models import Config, CropProfile, SensorReading, CaptureSession, BiometricMetric, AgronomicConclusion, User

class IConfigRepository(Protocol):
    def get(self) -> Config: ...
    def update(self, **kwargs) -> Config: ...

class ICropProfileRepository(Protocol):
    def get_by_type(self, crop_type: str) -> Optional[CropProfile]: ...
    def get_all(self) -> List[CropProfile]: ...
    def save_or_update(self, profile: CropProfile) -> CropProfile: ...

class ISensorRepository(Protocol):
    def add(self, reading: SensorReading) -> SensorReading: ...
    def bulk_add(self, readings: List[SensorReading]) -> int: ...
    def get_latest(self) -> Optional[SensorReading]: ...
    def get_recent(self, limit: int = 30) -> List[SensorReading]: ...
    def get_by_date(self, date_str: str) -> List[SensorReading]: ...
    def get_available_dates(self) -> List[str]: ...
    def find_nearest(self, target_timestamp) -> Optional[SensorReading]: ...
    def delete_by_date(self, date_str: str) -> int: ...

class ICaptureSessionRepository(Protocol):
    def get_by_id(self, session_id: int) -> Optional[CaptureSession]: ...
    def get_by_period_and_plant(self, period: str, plant_id: int) -> Optional[CaptureSession]: ...
    def get_all_by_plant(self, plant_id: int, order_asc: bool = False) -> List[CaptureSession]: ...
    def get_by_date_and_plant(self, date_str: str, plant_id: int) -> List[CaptureSession]: ...
    def get_available_dates(self, plant_id: int) -> List[str]: ...
    def save(self, session: CaptureSession) -> CaptureSession: ...
    def delete(self, session: CaptureSession) -> None: ...
    def delete_by_date(self, date_str: str, plant_id: int) -> int: ...

class IConclusionRepository(Protocol):
    def get_by_id(self, conclusion_id: int) -> Optional[AgronomicConclusion]: ...
    def get_filtered(self, plant_id: int, date_str: Optional[str] = None, period_type: Optional[str] = None) -> List[AgronomicConclusion]: ...
    def save(self, conclusion: AgronomicConclusion) -> AgronomicConclusion: ...
    def delete(self, conclusion: AgronomicConclusion) -> None: ...

class IUserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_username(self, username: str) -> Optional[User]: ...
    def get_all(self) -> List[User]: ...
    def save(self, user: User) -> User: ...
    def delete(self, user: User) -> None: ...
