from typing import Protocol, List, Dict, Any, Optional
import numpy as np
from domain.models import CropProfile

class ISegmentationStrategy(Protocol):
    """Contrato para estrategias de segmentación de imágenes (Pattern: Strategy)."""
    def create_mask(self, image: np.ndarray, profile: CropProfile) -> Optional[np.ndarray]: ...
    def extract_contours(self, mask: np.ndarray, min_area: int = 30) -> List[np.ndarray]: ...

class IBiometricCalculator(Protocol):
    """Contrato para cálculo de morfometría e índices agronómicos."""
    def calculate_cenital(self, image: np.ndarray, mask: np.ndarray, contours: List[np.ndarray], profile: CropProfile) -> Dict[str, Any]: ...
    def calculate_lateral(self, image: np.ndarray, mask: np.ndarray, contours: List[np.ndarray], profile: CropProfile) -> Dict[str, Any]: ...

class IVisionPipeline(Protocol):
    """Contrato del orquestador del pipeline visual."""
    def process_cenital(self, image_path: str, output_path: str, profile: CropProfile) -> Optional[Dict[str, Any]]: ...
    def process_lateral(self, image_path: str, output_path: str, profile: CropProfile) -> Optional[Dict[str, Any]]: ...
    def filter_and_average(self, cenital_results: List[Dict[str, Any]], lateral_results: List[Dict[str, Any]]) -> Dict[str, Any]: ...
